import Head from 'next/head';
import styled from 'styled-components';

const PageBody = styled.body`
  padding-top: 0;
  font-size: 12px;
  color: #777;
  background: #f9f9f9;
  font-family: 'Open Sans',sans-serif;
  margin-top:20px;
`

const Content = styled.div`
  display: flex;
  justify-content: center;
`

const BlogSection = styled.section`
  display: flex;
  flex-direction: column;
`

const Heading = styled.h1`
  margin: 20px 0;
  padding: 5px 0 10px;
  border-bottom: 1px solid #eee;
  font-weight: 500;
`

const BlogContainer = styled.div`
  position: relative;
  background: #fff;
  color: #999;
  transition: all .2s linear;
  -webkit-transition: all .2s linear;
  -moz-transition: all .2s linear;
  -ms-transition: all .2s linear;
  -o-transition: all .2s linear;
`

const ImgWrapper = styled.div`
  position: relative;
  display: block;
  overflow: hidden;
`

const BlogImg = styled.img`
  transition: all .4s ease;
  -webkit-transition: all .4s ease;
  -moz-transition: all .4s ease;
  -ms-transition: all .4s ease;
  -o-transition: all .4s ease;
`

const ImgOverlay = styled.div`
position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
  background-color: #3c8dbc;
  background-image: -moz-linear-gradient(top,#5fa4cc,#3c8dbc);
  background-image: -webkit-gradient(linear,0 0,0 100%,from(#5fa4cc),to(#3c8dbc));
  background-image: -webkit-linear-gradient(top,#5fa4cc,#3c8dbc);
  background-image: -o-linear-gradient(top,#5fa4cc,#3c8dbc);
  background-image: linear-gradient(to bottom,#5fa4cc,#3c8dbc);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#5fa4cc, endColorstr=#3c8dbc, GradientType=0);
  filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
  border: 6px solid #296282;
  transition: all .4s ease;
  -webkit-transition: all .4s ease;
  -moz-transition: all .4s ease;
  -ms-transition: all .4s ease;
  -o-transition: all .4s ease;

  &:hover {
    opacity: .9;
    transition: all .4s ease;
    -webkit-transition: all .4s ease;
    -moz-transition: all .4s ease;
    -ms-transition: all .4s ease;
    -o-transition: all .4s ease;
    transform: translateX(0%);
    -webkit-transform: translateX(0%);
    -moz-transform: translateX(0%);
    -ms-transform: translateX(0%);
    -o-transform: translateX(0%);
  }
`

const PostLike = styled.span`
  float: right;
  cursor: pointer;
`

const Media = styled.div`
  overflow: hidden;
  zoom: 1;
`

export default function Resources() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
      </Head>
      <PageBody>
        <Heading>Welcome to our blog</Heading>
        <Content>
          <BlogSection>
            <BlogContainer>
              <div className="panel-body">
                <ImgWrapper>
                  <a className="image-wrapper image-zoom cboxElement" href="#">
                    <BlogImg src="https://www.presentationmagazine.com/powerpoint-templates/00656/468slide1.jpg" alt="Photo of Blog" />
                    <ImgOverlay /> 
                  </a>
                </ImgWrapper>
                
                <h4>Headline</h4>
                <small className="text-muted">By <a href="#"><strong> John Doe</strong></a> |  Post on Jan 8, 2013  | 58 comments</small>
                
                <p className="m-top-sm m-bottom-sm">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros nibh, viverra a dui a, gravida varius velit. Nunc vel tempor nisi. Aenean id pellentesque mi, non placerat mi. Integer luctus accumsan tellus. Vivamus quis elit sit amet nibh lacinia suscipit eu quis purus. Vivamus tristique est non ipsum dapibus lacinia sed nec metus.
                </p>
                <a href="single_post.html"><i className="fa fa-angle-double-right"></i> Continue reading</a>
                <PostLike data-toggle="tooltip" data-original-title="I like this post!">
                  <i className="fa fa-heart"></i> <span className="like-count">25</span>
                </PostLike>
              </div>
            </BlogContainer>  
            <BlogContainer>
              <div className="panel-body">
                <ImgWrapper>
                  <a className="image-wrapper image-zoom cboxElement" href="#">
                    <BlogImg src="https://www.presentationmagazine.com/powerpoint-templates/00656/468slide1.jpg" alt="Photo of Blog" />
                    <ImgOverlay /> 
                  </a>
                </ImgWrapper>
                
                <h4>Headline</h4>
                <small className="text-muted">By <a href="#"><strong> John Doe</strong></a> |  Post on Jan 8, 2013  | 58 comments</small>
          
                <p className="m-top-sm m-bottom-sm">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros nibh, viverra a dui a, gravida varius velit. Nunc vel tempor nisi. Aenean id pellentesque mi, non placerat mi. Integer luctus accumsan tellus. Vivamus quis elit sit amet nibh lacinia suscipit eu quis purus. Vivamus tristique est non ipsum dapibus lacinia sed nec metus.
                </p>
                <a href="single_post.html"><i className="fa fa-angle-double-right"></i> Continue reading</a>
                <PostLike data-toggle="tooltip" data-original-title="I like this post!">
                  <i className="fa fa-heart"></i> <span className="like-count">25</span>
                </PostLike>
              </div>
            </BlogContainer>          
          </BlogSection>
        
          <BlogSection>
            <Heading>
              POPULAR POST
              <span className="line"></span>
            </Heading>
            <Media>
              <a className="pull-left" href="#">
                <BlogImg src="https://via.placeholder.com/60x60/9400D3/000000" alt="Popular Post" />
              </a>
              <Media>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
              </Media>
            </Media>  
            <Media>
              <a className="pull-left" href="#">
                <BlogImg src="https://via.placeholder.com/60x60/4B0082/000000" alt="Popular Post" />
              </a>
              <Media>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
              </Media>
            </Media>  
            <Media>
              <a className="pull-left" href="#">
                <BlogImg src="https://via.placeholder.com/60x60/E6E6FA/000000" alt="Popular Post" />
              </a>
              <Media>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
              </Media>
            </Media>    
            <Media>
              <a className="pull-left" href="#">
                <BlogImg src="https://via.placeholder.com/60x60/FFFACD/000000" alt="Popular Post" />
              </a>
              <Media>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
              </Media>
            </Media>    
            <Media>
              <a className="pull-left" href="#">
                <BlogImg src="https://via.placeholder.com/60x60/E0FFFF/000000" alt="Popular Post" />
              </a>
              <Media>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
              </Media>
            </Media>            
          </BlogSection>
        </Content>
      </PageBody>
    </>
  )
}