import Head from 'next/head';
import styled from 'styled-components';

const Container = styled.div`
  background-color: lightgray;
`

const Timeline = styled.div`
  width: 80%;
  margin: 20px auto;
  position: relative;

  &::before {
  content: '';
  display: block;
  position: absolute;
  left: 50%;
  top: 0;
  margin: 0 0 0 -1px;
  width: 2px;
  height: 100%;
  background: rgba(255,255,255,0.2);
  }
`

const Article = styled.article`
  width: 100%;
  margin: 0 0 20px 0;
  position: relative;

  &::after {
  content: '';
  display: block;
  clear: both;
  }
`

const DateCircle = styled.div`
  width: 40%;
  float: left;
  margin: 5px 0 0 0;
  border-radius: 6px;
`

const Date = styled.span`
  display: flex;
  justify-content: center;
  align-items: center;
  width: 70px;
  height: 70px;
  padding: 5px 0;
  position: absolute;
  top: 5%;
  left: 50%;
  margin: 0 0 0 -32px;
  border-radius: 100%;
  font-size: 12px;
  font-weight: 900;
  text-transform: uppercase;
  background: #25303B;
  color: rgba(255,255,255,0.5);
  border: 2px solid rgba(255,255,255,0.2);
  box-shadow: 0 0 0 7px #25303B;
`

export default function History() {
  return (
    <>
      <Head>
        <title>History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
      <Timeline>
        <Article>
          <DateCircle>
            <Date>
              <span class="day">30<sup>th</sup></span>
              <span class="month">Jan</span>
              <span class="year">2014</span>
            </Date>
            <h2>The Title</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis rutrum nunc, eget dictum massa. Nam faucibus felis nec augue adipiscing, eget commodo libero mattis.</p>
          </DateCircle>
        </Article>
        <Article>
          <DateCircle>
            <Date>
              <span class="day">26<sup>th</sup></span>
              <span class="month">Jan</span>
              <span class="year">2014</span>
            </Date>
            <h2>The Title</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis rutrum nunc, eget dictum massa. Nam faucibus felis nec augue adipiscing, eget commodo libero mattis.</p>
          </DateCircle>
        </Article>
      </Timeline>
      </Container>
    </>
  )
}