import Head from 'next/head';
import styled from 'styled-components';

const Hero = styled.div`
  display: flex;
  height: 90vh;
  justify-content: center;
  align-items: center;
  background-color: white;
`

const Heading = styled.h1`
  color: black;
  font-size: 10rem;
  font-weight: 900;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>New app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading>test</Heading>
      </Hero>

    </>
  )
}
